# Generated by Django 3.2.5 on 2021-09-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
