# Generated by Django 3.2.5 on 2021-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_auto_20210910_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
