# Generated by Django 3.2.5 on 2021-09-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_signup_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='photo',
        ),
    ]
