# Generated by Django 2.2.5 on 2021-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_auto_20210912_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, upload_to='static.images'),
        ),
    ]
