# Generated by Django 2.2.5 on 2021-09-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_auto_20210912_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='image',
        ),
    ]
