# Generated by Django 2.2.5 on 2021-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_remove_signup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
