# Generated by Django 2.2.5 on 2021-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
