# Generated by Django 2.2.5 on 2021-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0011_auto_20210912_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
