# Generated by Django 2.2.5 on 2021-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0012_auto_20210912_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200, null=True)),
                ('rmail', models.CharField(max_length=200, null=True)),
                ('rphone', models.CharField(max_length=200, null=True)),
                ('rorder', models.CharField(max_length=200, null=True)),
                ('rdate', models.CharField(max_length=200, null=True)),
                ('rid', models.CharField(max_length=200, null=True)),
                ('ridno', models.CharField(max_length=200, null=True)),
                ('rweight', models.CharField(max_length=200, null=True)),
                ('raddress', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
