# Generated by Django 2.2.5 on 2021-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rstatus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
