# Generated by Django 2.2.5 on 2021-09-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0015_auto_20210914_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='raddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='rdate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mail',
            new_name='rmail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='rorder',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='rphone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sid',
            new_name='rsid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sidno',
            new_name='rsidno',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='rstatus',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='weight',
            new_name='rweight',
        ),
    ]
