# Generated by Django 2.2.5 on 2021-09-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_auto_20210914_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
